blogapp/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf import settings
import os

from personal.views import (
    home_screen_view,
    returnassetlink,
)

from account.views import(
    registration_view,
    logout_view,
    login_view,
    account_view,
    changepasswordview,
    sendotp,
    changepasswordform,
    resetpassword,
    resetpasswordview,
)

from registerform.views import(
    create_subscription,
    load_district,
    load_subdistrict,
    load_postoffice,
    see_subscription,
    load_village,
)

from post.views import(
    show_feed,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name='home'),
    path('post/', include('post.urls', 'post')),
    path('register/', registration_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('login/', login_view, name='login'),
    path('account/', account_view, name='account'),
    path('subscribe/', create_subscription, name='subscribe'),
    path('see_subscription/', see_subscription, name='see_subscription'),
    path('ajax/load-district', load_district, name='load-district'),
    path('ajax/load-subdistrict', load_subdistrict, name='load-subdistrict'),
    path('ajax/load-postoffice', load_postoffice, name='load-postoffice'),
    path('ajax/load-village', load_village, name='load-village'),
    path('feed/', show_feed, name='feed'),
    path('.well-known/assetlinks.json', returnassetlink),
    path('changepassword/', changepasswordview, name='changepassword'),
    path('sendotp/<phone>', sendotp, name='sendotp'),
    path('changepasswordform/<phone>/<otp>',
         changepasswordform, name='changepasswordform'),
    path('resetpassword/', resetpassword, name='resetpassword'),
    path('resetpasswordview/<phone>', resetpasswordview, name='resetpasswordview'),

    path('', include('pwa.urls')),
    url(r'session_security/', include('session_security.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from post.views import(
    create_post_view,
    edit_post_view,
    delPost,
    likePost,
    detail_post_view,
)

app_name = 'post'

urlpatterns = [
    path('create', create_post_view, name='create'),
    path('<pk>/edit', edit_post_view, name='edit'),
    path('<pk>/delete', delPost, name='delete'),
    path('like', likePost, name='likepost'),
    path('<pk>', detail_post_view, name='detail'),
]

post/models.py
from django.db import models
from account.models import Account

# Create your models here.
from django.conf import settings
from datetime import datetime


def upload_location(instance, filename):
    file_path = 'image/post/{author_id}/{title}-{datetiming}-{filename}'.format(
        author_id=str(instance.author.id), title=str(instance.title), filename=filename,
        datetiming=datetime.now().strftime("%d/%m/%Y %H:%M:%S")
    )
    return file_path


def upload_video_location(instance, filename):
    file_path = 'video/post/{author_id}/{title}-{datetiming}-{filename}'.format(
        author_id=str(instance.author.id), title=str(instance.title), filename=filename,
        datetiming=datetime.now().strftime("%d/%m/%Y %H:%M:%S")
    )
    return file_path


class Post(models.Model):
    title = models.CharField(max_length=50, null=False, blank=False)
    body = models.TextField(max_length=5000, null=True, blank=True)
    image = models.ImageField(upload_to=upload_location, null=True, blank=True)
    videofile = models.FileField(
        upload_to=upload_video_location, null=True, blank=True)
    date_published = models.DateTimeField(
        auto_now_add=True, verbose_name="date published")
    date_updated = models.DateTimeField(
        auto_now=True, verbose_name="date updateddate_updated")
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Like(models.Model):
    user = models.ManyToManyField(Account, related_name="likingUser")
    post = models.OneToOneField(Post, on_delete=models.CASCADE)

    @classmethod
    def like(cls, post, liking_user):
        obj, create = cls.objects.get_or_create(post=post)
        obj.user.add(liking_user)

    @classmethod
    def dislike(cls, post, disliking_user):
        obj, create = cls.objects.get_or_create(post=post)
        obj.user.remove(disliking_user)

    def getnooflikes(self):
        return self.user.count()

    def __str__(self):
        return str(self.post)

post/forms.py
from django import forms

from post.models import Post

class CreatePostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=['title','body','image','videofile']

class UpdatePostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=['title','body','image','videofile']

    def save(self,commit=True):
        post=self.instance
        post.title=self.cleaned_data['title']
        if self.cleaned_data['body']:
            post.body=self.cleaned_data['body']

        if self.cleaned_data['image']:
            post.image=self.cleaned_data['image']

        if self.cleaned_data['videofile']:
            post.videofile=self.cleaned_data['videofile']

        if commit:
            post.save()
        return post

post/views.py
from django.shortcuts import render, redirect, get_object_or_404
from registerform.models import RegistrationForm
from post.models import Post, Like
from operator import attrgetter
from post.forms import CreatePostForm, UpdatePostForm
from account.models import Account
from django.db.models import Q
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
import json
from django.http import HttpResponse

BLOG_POSTS_PER_PAGE = 10

# Create your views here.


def create_post_view(request):

    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('login')

    registration = RegistrationForm.objects.filter(user=request.user)
    if not registration:
        return redirect('subscribe')
    if not registration[0].is_approved:
        return redirect('see_subscription')
    if registration[0].membertype != 'Life Member':
        return redirect('feed')

    form = CreatePostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        author = Account.objects.filter(username=user.username).first()
        obj.author = author
        obj.save()
        return redirect('feed')

    context['form'] = form

    context['registration'] = registration[0]

    return render(request, 'post/create_post.html', context)


def edit_post_view(request, pk):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('login')

    registration = RegistrationForm.objects.filter(user=request.user)
    if not registration:
        return redirect('subscribe')
    if not registration[0].is_approved:
        return redirect('see_subscription')
    if registration[0].membertype != 'Life Member':
        return redirect('feed')

    post = get_object_or_404(Post, pk=pk)

    if request.POST:
        form = UpdatePostForm(request.POST or None,
                              request.FILES or None, instance=post)
        if form.is_valid():
            obj = form.save(commit=False)
            if request.POST.get('clear_image_image'):
                obj.image = None
            if request.POST.get('clear_image_videofile'):
                obj.videofile = None
            obj.save()
            context['success_message'] = "Updated"
            post = obj

    form = UpdatePostForm(
        initial={
            'title': post.title,
            'body': post.body or '',
            'image': post.image or None,
            'videofile': post.videofile or None,
        }
    )
    context['form'] = form
    context['registration'] = registration[0]
    return render(request, 'post/edit_post.html', context)


def get_post_queryset(request, query=None):
    queryset = []
    queries = query.split(" ")
    for q in queries:
        posts = Post.objects.filter(
            Q(title__icontains=q) |
            Q(body__icontains=q)
        ).distinct()

        for post in posts:
            is_liked = Like.objects.filter(post=post, user=request.user)
            likes = Like.objects.filter(post=post)
            if is_liked:
                post.is_liked = True
            if likes:
                post.nooflike = likes[0].getnooflikes()
            else:
                post.nooflike = 0
            queryset.append(post)

    return list(set(queryset))


def get_post_queryset_account(query=None, account=None):
    queryset = []
    queries = query.split(" ")
    for q in queries:
        posts = Post.objects.filter(author=account).filter(
            Q(title__icontains=q) |
            Q(body__icontains=q)
        ).distinct()

        for post in posts:
            queryset.append(post)

    return list(set(queryset))


def show_feed(request):
    if not request.user.is_authenticated:
        return redirect('login')
    registration = RegistrationForm.objects.filter(user=request.user)
    if not registration:
        return redirect('subscribe')
    if not registration[0].is_approved:
        return redirect('see_subscription')

    context = {}
    context['registration'] = registration[0]

    query = ''
    if request.GET:
        query = request.GET.get('q', '')
        context['query'] = str(query)

    posts = sorted(get_post_queryset(request, query),
                   key=attrgetter('date_updated'), reverse=True)

    page = request.GET.get('page', 1)
    posts_paginator = Paginator(posts, BLOG_POSTS_PER_PAGE)

    try:
        posts = posts_paginator.page(page)
    except PageNotAnInteger:
        posts = posts_paginator.page(BLOG_POSTS_PER_PAGE)
    except EmptyPage:
        posts = posts_paginator.page(posts_paginator.num_pages)

    context['posts'] = posts

    return render(request, 'post/feed.html', context)


def delPost(request, pk):
    if not request.user.is_authenticated:
        return redirect('login')
    registration = RegistrationForm.objects.filter(user=request.user)
    if not registration:
        return redirect('subscribe')
    if not registration[0].is_approved:
        return redirect('see_subscription')
    post_ = Post.objects.filter(pk=pk)
    post_.delete()
    return redirect('feed')


def likePost(request):
    resp = {}
    post_id = request.GET.get("likeId", "")
    post = Post.objects.get(pk=post_id)
    user = request.user
    like = Like.objects.filter(post=post, user=user)
    liked = False
    if like:
        Like.dislike(post, user)
        resp["nofolikes"] = Like.objects.filter(
            post=post).first().getnooflikes()
    else:
        liked = True
        Like.like(post, user)
        resp["nofolikes"] = Like.objects.filter(
            post=post).first().getnooflikes()

    resp["liked"] = liked
    response = json.dumps(resp)
    return HttpResponse(response, content_type="application/json")


def detail_post_view(request, pk):
    context = {}
    post = get_object_or_404(Post, pk=pk)
    is_liked = Like.objects.filter(post=post, user=request.user)
    likes = Like.objects.filter(post=post)
    if is_liked:
        post.is_liked = True
    if likes:
        post.nooflike = likes[0].getnooflikes()
    else:
        post.nooflike = 0
    context['post'] = post
    return render(request, 'post/detail_post.html', context)

post/templates/post/create_post.html
{% extends 'base.html' %}

{% block content %}

<style type="text/css">
    .create-form {
          width: 100%;
          max-width: 100%;
          padding: 15px;
          margin: auto;
        }
  
        .submit-button{
            max-width: 200px;
        }
  </style>
  
  <div class="container">
      <div class="row">
          <div class="col-lg-7 offset-lg-1">
              <form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}
  
                  <!-- title -->
                  <div class="form-group mb-4">
                      <label class="mb-4" for="id_title">Title*</label>
                      <input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required autofocus>
                  </div>
  
                  <!-- Body -->
                  <div class="form-group mb-4">
                      <label class="mb-4" for="id_body">Content</label>
                      <textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="This post is about..."></textarea>
                  </div>
  
                  <!-- Image -->
                  <div class="form-group mb-4">
                      <label for="id_image">Image</label>
                      <input  type="file" name="image" id="id_image" accept="image/*">
                  </div>

                  <div class="form-group mb-4">
                    <label for="id_videofile">Video(mp4 supported)</label>
                    <input  type="file" name="videofile" id="id_videofile" accept="video/mp4">
                </div>
                {% for field in form %}
                <p>
            {% for error in field.errors %}
            <p style="color: red;">{{field}} : {{error}}</p>
            {% endfor %}
                </p>
                {% endfor %}
  
                  <!-- Submit btn -->
                  <button class="submit-button btn btn-lg btn-primary btn-block" type="submit">POST</button>
              </form>	
          </div>
      </div>
  </div>

{% endblock content %}

post/templates/post/detail_post.html
{% extends 'base.html' %}

{% block content %}
<style>
    .card{
        max-width: 700px;
    }
    .container{
        padding: 20px;
    }
</style>

<div class="container">
<div class="row">

<div class="card m-auto">
    {% if post.image %}
<img class="card-img-top" src="{{post.image.url}}" alt="">
{% endif %}
{% if post.videofile %}
            <video controls>
                <source src="{{post.videofile.url}}" type="video/mp4">
              Your browser does not support the video tag.
              </video>
            {% endif %}
    <div class="card-body my-2">
<h2 class="card-title">{{post.title}}</h2>
{% if post.body %}
<p class="card-text">{{post.body}}</p>
{% endif %}
<p class="card-text" id="nofolikes{{post.pk}}">Likes - {{post.nooflike}}</p>
<button class="btn btn-light like" style="border-color: red;" id="{{post.pk}}">
    {% if post.is_liked %}
  <a href="{% url 'post:likepost' %}" style="color: red;text-decoration: none;" id="like_text{{post.pk}}">Liked</a>
  {% else %}
  <a href="{% url 'post:likepost' %}" style="color: red;text-decoration: none;" id="like_text{{post.pk}}">Like</a>
  {% endif %}
  </button>
    </div>
    <div class="card-footer text-muted">
        Updated on {{post.date_updated}} by {{post.author}}
    </div>
</div>

</div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $(".like").click(function(e) { 
    var id =  this.id ; 
    var href = $('.like').find('a').attr('href');
    e.preventDefault();  // don't follow the link

    $.ajax({
        url: href,
        data: {'likeId':id},
        success:function(response)
        {
          if(response.liked){
            $("#like_text"+id).html("Liked");
			$("#nofolikes"+id).html("Likes - "+response.nofolikes);
          }else{
            $("#like_text"+id).html("Like");
			$("#nofolikes"+id).html("Likes - "+response.nofolikes);
          }
        }
    });

  });
</script>


{% endblock content %}

post/templates/post/edit_post.html
{% extends 'base.html' %}


{% block content %}
<style type="text/css">
   .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}

	.image {
	  opacity: 1;
	  transition: .5s ease;
	  backface-visibility: hidden;
	}

	.middle {
	  transition: .5s ease;
	  opacity: 0;
	  position: absolute;
	  text-align: center;
	  top: 50%;
	  left: 50%;
	  transform: translate(-50%, -50%);
	
	}
	.image-group{
		position: relative;
  		text-align: center;
  		cursor:pointer;
	}

	.image-group:hover .image {
	  opacity: 0.3;
	}

	.image-group:hover .middle {
	  opacity: 1;
	}

	.text {
	  margin: auto;
	  background-color: #4CAF50;
	  color: white;
	  font-size: 15px;
	  padding: 15px;
	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}

			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group mb-4">
					<label for="id_title">Title*</label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" value="{{form.initial.title}}" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group mb-4">
					<label for="id_body">Content</label>
					<textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="Your Content here..." >{{form.initial.body}}</textarea>
				</div>
				{% for field in form %}
                <p>
            {% for error in field.errors %}
            <p style="color: red;">{{field}} : {{error}}</p>
            {% endfor %}
                </p>
                {% endfor %}

				<!-- Image -->
				<div class="form-group mb-4">
                    <label for="id_image">Image
						{% if form.initial.image %}
						Previous Image - <a href="{{form.initial.image.url}}" target="_blank">Click Here</a>
						{% endif %}
					</label>
                    <br>
                    <input type="file" name="image" id="id_image" accept="image/*">
				</div>

                <div class="form-group mb-4">
                    <label for="id_videofile">Video(mp4 supported) 
						{% if form.initial.videofile %}
						Previous Video - <a href="{{form.initial.videofile.url}}" target="_blank">Click Here</a>
						{% endif %}
					</label>
                    <br>
                    <input type="file" name="videofile" id="id_videofile" accept="video/mp4">
				</div>
				

				{% for error in errors %}
							<p style="color: red">{{ error }}</p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
						<p>{{form.non_field_errors}}</p>
					</div>
				{% endif %}

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Update</button>
			</form>	
		</div>
	</div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script type="text/javascript">
	$(document).ready(function() {
        console.log('hello');
		$('input[type=file]').each(function() {
			$(this).after(' <input type="checkbox" name="clear_image_'+$(this).attr('name')+'"/> Clear');
		});
	});
	</script>

{% endblock content %}

post/templates/post/feed.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style type="text/css">

	@media (max-width: 768px) { 
		.right-column{
			margin-left: 0px;
		}
	}

	@media (min-width: 768px) { 
		.right-column{
			margin-left: 20px;
		}
	}

	.blog-post-container{
		margin-bottom: 20px;
		width: 100%;
	}
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}

	.left-column{
		padding:0px;
	}

	.right-column{
		padding:0px;
	}
	.lead{
		font-size: 17px;
	}
	.search-bar{
max-width: 500px;
width: 100%;
}
</style>
<div class="container">
	<div class="row">
		<div class='search-bar mt-2 offset-lg-1'>
			<form method="GET">
			  <input type="text" class="form-control" name="q" id="id_q" placeholder="Search..." value="{{query}}">
			</form>
			  </div>

		<!-- blog feed -->
		<div class="left-column col-lg-7 offset-lg-1 mt-3">

			<!-- Top 'create post' bar -->
			<div class="d-lg-none mb-3">
				<div class="card m-auto d-flex flex-column p-3">
					<p class="lead">Only Life Members can create a post</p>
					{% if registration.membertype == 'Life Member' %}
					<p class="m-auto"><a class="btn btn-primary" href="{% url 'post:create' %}">Create post</a></p>
					{% endif %}
				</div>
			</div>
			<!-- end Top 'create post' bar -->

			<!-- Blog posts-->
			<div class="infinite-container">
			{% if posts %}
			{% for post in posts %}
				<div class="blog-post-container">
					{% include 'post/snippets/post_snippet.html' with post=post %}
				</div>
			{% endfor %}
			{% else %}
			<div class="blog-post-container">
				{% include 'post/snippets/post_snippet.html' with query=query %}
			</div>
			{% endif %}
		</div>
			<!-- End Blog posts-->
			{% include 'post/snippets/post_pagination.html' with posts=posts %}
		</div>
		<!-- end blog feed -->
		<div class="d-flex position-fixed" style="top:35vh;left:46vw">
			<button class="btn btn-primary loading" style="display: none;">
				<span class="spinner-border spinner-border-sm"></span>
				Loading...
			  </button>
		</div>
		


		<!-- Right 'create post' column  -->
		<div class="right-column col-lg-3 d-lg-flex d-none flex-column mt-3">

			<div class="card create-post-bar d-flex flex-column p-3">
				<p class="lead">Only Life Members can create a post</p>
				{% if registration.membertype == 'Life Member' %}
				<p class="m-auto"><a class="btn btn-primary" href="{% url 'post:create' %}">Create post</a></p>
				{% endif %}
			</div>
		
		</div>
		<!-- end Right 'create post' column  -->

	</div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/infinite.min.js' %}"></script>
<script>
	var infinite=new Waypoint.Infinite({
		element:$('.infinite-container')[0],
		offset:'bottom-in-view',

		onBeforePageLoad: function(){
			$('.loading').css("display","block")
		},
		onAfterPageLoad: function(){
			$('.loading').css("display","none")
		}
	})
</script>
<script>
	$('.delete').submit(function (e){
		var id=this.id;
		var href=this.action;
		e.preventDefault();
		var z=confirm('Are You Sure, You want to delete this Post');
		if(z){
			$.ajax({
				url:href,
				data:{},
			})
			$('#'+id).fadeOut(1000);
		}
		
	})

	$(".like").click(function(e) { 
    var id =  this.id ; 
    var href = $('.like').find('a').attr('href');
    e.preventDefault();  // don't follow the link

    $.ajax({
        url: href,
        data: {'likeId':id},
        success:function(response)
        {
          if(response.liked){
            $("#like_text"+id).html("Liked");
			$("#nofolikes"+id).html("Likes - "+response.nofolikes);
          }else{
            $("#like_text"+id).html("Like");
			$("#nofolikes"+id).html("Likes - "+response.nofolikes);
          }
        }
    });

  });
</script>

{% endblock content %}