blogapp/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf import settings
import os

from personal.views import (
    home_screen_view,
    returnassetlink,
)

from account.views import(
    registration_view,
    logout_view,
    login_view,
    account_view,
    changepasswordview,
    sendotp,
    changepasswordform,
    resetpassword,
    resetpasswordview,
)

from registerform.views import(
    create_subscription,
    load_district,
    load_subdistrict,
    load_postoffice,
    see_subscription,
    load_village,
)

from post.views import(
    show_feed,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name='home'),
    path('post/', include('post.urls', 'post')),
    path('register/', registration_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('login/', login_view, name='login'),
    path('account/', account_view, name='account'),
    path('subscribe/', create_subscription, name='subscribe'),
    path('see_subscription/', see_subscription, name='see_subscription'),
    path('ajax/load-district', load_district, name='load-district'),
    path('ajax/load-subdistrict', load_subdistrict, name='load-subdistrict'),
    path('ajax/load-postoffice', load_postoffice, name='load-postoffice'),
    path('ajax/load-village', load_village, name='load-village'),
    path('feed/', show_feed, name='feed'),
    path('.well-known/assetlinks.json', returnassetlink),
    path('changepassword/', changepasswordview, name='changepassword'),
    path('sendotp/<phone>', sendotp, name='sendotp'),
    path('changepasswordform/<phone>/<otp>',
         changepasswordform, name='changepasswordform'),
    path('resetpassword/', resetpassword, name='resetpassword'),
    path('resetpasswordview/<phone>', resetpasswordview, name='resetpasswordview'),

    path('', include('pwa.urls')),
    url(r'session_security/', include('session_security.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from post.views import(
    create_post_view,
    edit_post_view,
    delPost,
    likePost,
    detail_post_view,
)

app_name = 'post'

urlpatterns = [
    path('create', create_post_view, name='create'),
    path('<pk>/edit', edit_post_view, name='edit'),
    path('<pk>/delete', delPost, name='delete'),
    path('like', likePost, name='likepost'),
    path('<pk>', detail_post_view, name='detail'),
]

registerform/models.py
from django.db import models
from django.conf import settings
from django.dispatch import receiver
from django.db.models.signals import pre_save
from address.models import Address
from django.db.models import Q
from django.core.mail import send_mail
from django.core.mail import EmailMessage
import requests

import threading


class SMSThread(threading.Thread):

    def __init__(self, requests, url, headers, params):
        self.requests = requests
        self.url = url
        self.headers = headers
        self.params = params
        threading.Thread.__init__(self)

    def run(self):
        self.requests.request(
            "POST", self.url, headers=self.headers, params=self.params)

# Create your models here.


class RegistrationForm(models.Model):
    class MemberType(models.TextChoices):
        LIFE_MEMBER = 'Life Member'
        ACTIVE_MEMBER = 'Active Member'
        GENERAL_MEMBER = 'General Member'

    class MemberCategory(models.TextChoices):
        ORDINARY = 'Ordinary'
        TEMPLE_MANAGER = 'Temple Manager'
        PROHITS = 'Prohits'

    class Area(models.TextChoices):
        URBAN = 'Urban'
        RURAL = 'Rural'

    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)
    membertype = models.CharField(
        max_length=50, choices=MemberType.choices, default=MemberType.GENERAL_MEMBER)
    membercategory = models.CharField(
        max_length=50, choices=MemberCategory.choices, default=MemberCategory.ORDINARY)
    area = models.CharField(
        max_length=50, choices=Area.choices, default=Area.RURAL)
    state = models.CharField(null=False, max_length=100, blank=False)
    district = models.CharField(null=False, max_length=100, blank=False)
    subdistrict = models.CharField(null=False, max_length=100, blank=False)
    postoffice = models.CharField(null=False, max_length=100, blank=False)
    village = models.CharField(null=False, max_length=100, blank=False)
    templename = models.CharField(null=True, max_length=100, blank=True)
    code = models.CharField(max_length=20, default='notgiven')
    is_approved = models.BooleanField(default=False)

    def __str__(self):
        return self.user.email


@receiver(pre_save, sender=RegistrationForm, dispatch_uid='approved')
def approved(sender, instance, **kwargs):
    if instance.is_approved and RegistrationForm.objects.filter(pk=instance.pk, is_approved=False).exists():

        if(instance.membertype == 'Life Member'):
            membertype = 'L'
        elif(instance.membertype == 'Active Member'):
            membertype = 'A'
        else:
            membertype = 'G'

        if(instance.membercategory == 'Ordinary'):
            membercategory = 'O'
        elif(instance.membercategory == 'Temple Manager'):
            membercategory = 'T'
        else:
            membercategory = 'P'

        if(instance.state == 'ODISHA'):
            state = '19'
        elif(instance.state == 'DELHI'):
            state = '34'

        district = list(Address.objects.filter(state=instance.state).order_by(
            'district').values_list('district', flat=True).distinct()).index(instance.district)+1
        if district < 10:
            district = str(district)
            district = '0'+district
        else:
            district = str(district)

        subdistrict = list(Address.objects.filter(state=instance.state).filter(district=instance.district).order_by(
            'subdistrict').values_list('subdistrict', flat=True).distinct()).index(instance.subdistrict)+1
        if subdistrict < 10:
            subdistrict = str(subdistrict)
            subdistrict = '0'+subdistrict
        else:
            subdistrict = str(subdistrict)

        postoffice = list(Address.objects.filter(state=instance.state).filter(district=instance.district).filter(
            subdistrict=instance.subdistrict).order_by('officename').values_list('officename', flat=True).distinct()).index(instance.postoffice)+1
        if postoffice < 10:
            postoffice = str(postoffice)
            postoffice = '0'+postoffice
        else:
            postoffice = str(postoffice)

        village = list(Address.objects.filter(state=instance.state).filter(district=instance.district).filter(subdistrict=instance.subdistrict).filter(
            officename=instance.postoffice).order_by('villagename').values_list('villagename', flat=True).distinct()).index(instance.village)+1
        if village < 100 and village >= 10:
            village = str(village)
            village = '0'+village
        elif village < 10:
            village = str(village)
            village = '00'+village
        else:
            village = str(village)

        samevillagepeople = RegistrationForm.objects.filter(state=instance.state).filter(district=instance.district).filter(
            subdistrict=instance.subdistrict).filter(postoffice=instance.postoffice).filter(village=instance.village).filter(~Q(code='notgiven')).order_by('code')
        indexn = 0
        index = 0
        for villager in samevillagepeople:
            indexn = indexn+1
            index = indexn
            if index < 100 and index >= 10:
                index = str(index)
                index = '0'+index
            elif index < 10:
                index = str(index)
                index = '00'+index
            else:
                index = str(index)
            if index != villager.code[-3:]:
                personno = index
                instance.code = membertype+membercategory+state + \
                    district+subdistrict+postoffice+village+personno

                mesagge = 'Your ABSS subscrtion is now accepted. Check out in the app'
                # sendemail = EmailMessage(
                #     subject,
                #     mesagge,
                #     from_email,
                #     [instance.user.email],
                # )
                # EmailThread(sendemail).start()
                querystring = {"from": "+13093160712", "body": mesagge,
                               "to": "+91"+str(instance.user.phone)}
                # requests.request(
                #     "POST", url, headers=headers, params=querystring)
                SMSThread(requests, settings.SMS_URL,
                          settings.SMS_HEADERS, querystring).start()
                return
        num_index = int(index)
        if(len(samevillagepeople) == num_index):
            personno = num_index+1
            print(personno)
            if personno < 100 and personno >= 10:
                personno = str(personno)
                personno = '0'+personno
            elif personno < 10:
                personno = str(personno)
                personno = '00'+personno
            else:
                personno = str(personno)
        instance.code = membertype+membercategory+state + \
            district+subdistrict+postoffice+village+personno

        mesagge = 'Your ABSS subscrtion is now accepted. Check out in the app'
        # sendemail = EmailMessage(
        #     subject,
        #     mesagge,
        #     from_email,
        #     [instance.user.email],
        # )
        # EmailThread(sendemail).start()
        querystring = {"from": "+13093160712", "body": mesagge,
                       "to": "+91"+str(instance.user.phone)}
        SMSThread(requests, settings.SMS_URL,
                  settings.SMS_HEADERS, querystring).start()

registerform/forms.py
from django import forms
from django.forms import Form
from django.forms import CharField,TextInput
from address.models import Address
from registerform.models import RegistrationForm

class RegistrationFormSearch(Form):
    state=CharField(required=False,widget=TextInput(
        attrs={
            'filter_method':'__icontains'
        }
    ))
    district=CharField(required=False,widget=TextInput(
        attrs={
            'filter_method':'__icontains'
        }
    ))
    subdistrict=CharField(required=False,widget=TextInput(
        attrs={
            'filter_method':'__icontains'
        }
    ))
    postoffice=CharField(required=False,widget=TextInput(
        attrs={
            'filter_method':'__icontains'
        }
    ))
    village=CharField(required=False,widget=TextInput(
        attrs={
            'filter_method':'__icontains'
        }
    ))

class RegistrationCreationFrom(forms.ModelForm):
    class Meta:
        model=RegistrationForm
        fields = ['membertype','membercategory','area','state','district','subdistrict','postoffice','village','templename']

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['state'].queryset=list(Address.objects.order_by('state').values_list('state',flat=True).distinct())
        self.fields['district'].queryset=Address.objects.none()
        self.fields['subdistrict'].queryset=Address.objects.none()
        self.fields['postoffice'].queryset=Address.objects.none()
        self.fields['village'].queryset=Address.objects.none()

        if 'state' in self.data:
            try:
                state=self.data.get('state_id')
                self.fields['district'].queryset=list(Address.objects.filter(state=state).order_by('district').values_list('district',flat=True).distinct())
            except(ValueError,TypeError):
                pass

            if 'district' in self.data:
                try:
                    state=self.data.get('state_id')
                    district=self.data.get('district_id')
                    self.fields['subdistrict'].queryset=list(Address.objects.filter(state=state).filter(district=district).order_by('subdistrict').values_list('subdistrict',flat=True).distinct())
                except(ValueError,TypeError):
                    pass

                if 'subdistrict' in self.data:
                    try:
                        state=self.data.get('state_id')
                        district=self.data.get('district_id')
                        subdistrict=self.data.get('subdistrict_id')
                        self.fields['postoffice'].queryset=list(Address.objects.filter(state=state).filter(district=district).filter(subdistrict=subdistrict).order_by('officename').values_list('officename',flat=True).distinct())
                    except(ValueError,TypeError):
                        pass

                    if 'postoffice' in self.data:
                        try:
                            state=self.data.get('state_id')
                            district=self.data.get('district_id')
                            subdistrict=self.data.get('subdistrict_id')
                            postoffice=self.data.get('postoffice_id') 
                            self.fields['village'].queryset=list(Address.objects.filter(state=state).filter(district=district).filter(subdistrict=subdistrict).filter(officename=postoffice).order_by('villagename').values_list('villagename',flat=True).distinct())
                        except(ValueError,TypeError):
                            pass

registerform/views.py
from django.shortcuts import render, redirect
from registerform.models import RegistrationForm
from registerform.forms import RegistrationCreationFrom
from address.models import Address
from account.models import Account

# Create your views here.


def create_subscription(request):
    if not request.user.is_authenticated:
        return redirect('login')
    registration = RegistrationForm.objects.filter(user=request.user)

    if(registration):
        return redirect('see_subscription')

    form = RegistrationCreationFrom()
    if request.method == 'POST':
        form = RegistrationCreationFrom(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            user = Account.objects.filter(
                username=request.user.username).first()
            obj.user = user
            obj.save()
            return redirect('see_subscription')
    states = list(Address.objects.order_by(
        'state').values_list('state', flat=True).distinct())
    return render(request, 'registerform/register.html', {'form': form, 'states': states})


def see_subscription(request):
    if not request.user.is_authenticated:
        return redirect('login')
    registration = RegistrationForm.objects.filter(user=request.user)

    if(not registration):
        return redirect('subscribe')

    return render(request, 'registerform/see_registration.html', {'registration': registration[0]})


def load_district(request):
    if not request.user.is_authenticated:
        return redirect('login')
    registration = RegistrationForm.objects.filter(user=request.user)

    if(registration):
        return redirect('see_subscription')
    state = request.GET.get('state_id')
    districts = list(Address.objects.filter(state=state).order_by(
        'district').values_list('district', flat=True).distinct())
    return render(request, 'registerform/district_dropdown_list.html', {'districts': districts})


def load_subdistrict(request):
    if not request.user.is_authenticated:
        return redirect('login')
    registration = RegistrationForm.objects.filter(user=request.user)

    if(registration):
        return redirect('see_subscription')
    state = request.GET.get('state_id')
    district = request.GET.get('district_id')
    subdistricts = list(Address.objects.filter(state=state).filter(district=district).order_by(
        'subdistrict').values_list('subdistrict', flat=True).distinct())
    return render(request, 'registerform/subdistrict_dropdown_list.html', {'subdistricts': subdistricts})


def load_postoffice(request):
    if not request.user.is_authenticated:
        return redirect('login')
    registration = RegistrationForm.objects.filter(user=request.user)

    if(registration):
        return redirect('see_subscription')
    state = request.GET.get('state_id')
    district = request.GET.get('district_id')
    subdistrict = request.GET.get('subdistrict_id')
    postoffices = list(Address.objects.filter(state=state).filter(district=district).filter(
        subdistrict=subdistrict).order_by('officename').values_list('officename', flat=True).distinct())
    return render(request, 'registerform/postoffice_dropdown_list.html', {'postoffices': postoffices})


def load_village(request):
    if not request.user.is_authenticated:
        return redirect('login')
    registration = RegistrationForm.objects.filter(user=request.user)

    if(registration):
        return redirect('see_subscription')
    state = request.GET.get('state_id')
    district = request.GET.get('district_id')
    subdistrict = request.GET.get('subdistrict_id')
    postoffice = request.GET.get('postoffice_id')
    villages = list(Address.objects.filter(state=state).filter(district=district).filter(subdistrict=subdistrict).filter(
        officename=postoffice).order_by('villagename').values_list('villagename', flat=True).distinct())
    return render(request, 'registerform/village_dropdown_list.html', {'villages': villages})

registerform/templates/registerform/district_dropdown_list.html
<option value="">---------</option>
{% for district in districts %}
<option value="{{ district }}">{{ forloop.counter }} {{ district }}</option>
{% endfor %}

registerform/templates/registerform/postoffice_dropdown_list.html
<option value="">---------</option>
{% for postoffice in postoffices %}
<option value="{{ postoffice }}">{{ forloop.counter }} {{ postoffice }}</option>
{% endfor %}

registerform/templates/registerform/register.html
{% extends 'base.html' %}

{% block content %}
<style>
    .form-signin {
  width: 100%;
  max-width: 500px;
  padding: 15px;
  margin: auto;
}
.form-signin select {
  margin-bottom: 10px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}

.form-signin input {
  margin-bottom: 10px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}
</style>

<div class="form-signin">
<form method="POST" id="registerForm" data-districts-url="{% url 'load-district' %}" data-subdistricts-url="{% url 'load-subdistrict' %}" data-postoffices-url="{% url 'load-postoffice' %}" data-villages-url="{% url 'load-village' %}">
    {% csrf_token %}
    <!-- {{ form.as_p }} -->
    <h1 class="h3 mb-3 fw-normal">Enter Account Details</h1>
    <label class="mb-3">Choose Member Type*</label>
    <select required class="form-control" name="{{ form.membertype.name }}">
        {% for instance in form.membertype %}
            <option value="{{ instance.pk }}">{{ instance }}</option>
        {% endfor %}
    </select>
    <label class="mb-3">Choose Member Category*</label>
    <select required class="form-control" name="{{ form.membercategory.name }}">
        {% for instance in form.membercategory %}
            <option value="{{ instance.pk }}">{{ instance }}</option>
        {% endfor %}
    </select>
    <label class="mb-3">Choose Area*</label>
    <select required class="form-control" name="{{ form.area.name }}">
        {% for instance in form.area %}
            <option value="{{ instance.pk }}">{{ instance }}</option>
        {% endfor %}
    </select>
    <label class="mb-3">Choose State*</label>
    <select class="form-control" name="state" id="id_state" required>
        <option value="">---------</option>
        {% for state in states %}
        <option value="{{ state }}">{{ forloop.counter }} {{ state }}</option>
        {% endfor %}
    </select>
    <label class="mb-3">Choose District*</label>
    <select class="form-control" name="district" id="id_district" required></select>
    <label class="mb-3">Choose Sub District*</label>
    <select class="form-control" name="subdistrict" id="id_subdistrict" required></select>
    <label class="mb-3">Choose Post Office Name*</label>
    <select class="form-control" name="postoffice" id="id_postoffice" required></select>
    <label class="mb-3">Choose Village/Area Name*</label>
    <select class="form-control" name="village" id="id_village" required></select>
    <label class="mb-3">Enter Temple Name in which Working if Any</label>
    <input class="form-control" type="text" name="templename">
    <button class="w-100 btn btn-lg btn-primary" type="submit">Register</button>
</form>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $('#id_state').change(function(){
        const url=$('#registerForm').attr("data-districts-url");
        const stateId=$(this).val();
        $('#id_postoffice').html('')
        $('#id_subdistrict').html('')
        $('#id_district').html('')
        $('#id_village').html('')
        

        $.ajax({
            url:url,
            data:{
                'state_id':stateId
            },
            success:function(data){
                $('#id_district').html(data);
            }
        })
    })
    $('#id_district').change(function(){
        const url=$('#registerForm').attr("data-subdistricts-url");
        const stateId=$('#id_state').val()
        const districtId=$(this).val();
        $('#id_postoffice').html('')
        $('#id_subdistrict').html('')
        $('#id_village').html('')

        $.ajax({
            url:url,
            data:{
                'state_id':stateId,
                'district_id':districtId,
            },
            success:function(data){
                $('#id_subdistrict').html(data);
            }
        })
    })
    $('#id_subdistrict').change(function(){
        const url=$('#registerForm').attr("data-postoffices-url");
        const stateId=$('#id_state').val()
        const districtId=$('#id_district').val();
        const subdistrictId=$(this).val();
        $('#id_postoffice').html('')
        $('#id_village').html('')
        

        $.ajax({
            url:url,
            data:{
                'state_id':stateId,
                'district_id':districtId,
                'subdistrict_id':subdistrictId,
            },
            success:function(data){
                $('#id_postoffice').html(data);
            }
        })
    })
    $('#id_postoffice').change(function(){
        const url=$('#registerForm').attr("data-villages-url");
        const stateId=$('#id_state').val()
        const districtId=$('#id_district').val();
        const subdistrictId=$('#id_subdistrict').val();
        const postofficeId=$(this).val();
        $('#id_village').html('')
        

        $.ajax({
            url:url,
            data:{
                'state_id':stateId,
                'district_id':districtId,
                'subdistrict_id':subdistrictId,
                'postoffice_id':postofficeId,
            },
            success:function(data){
                $('#id_village').html(data);
            }
        })
    })
</script>

{% endblock content %}

registerform/templates/registerform/see_registration.html
{% extends 'base.html' %}

{% block content %}
<div class="container text-center">
    {% if registration.is_approved %}
    <h1 class="h3 mb-3 fw-normal">Your Code is {{ registration.code }}</h1>
    <h1 class="h3 mb-3 fw-normal">Your Member Type is {{ registration.membertype }}</h1>
    <h1 class="h3 mb-3 fw-normal">Your Member Category is {{ registration.membercategory }}</h1>
    <h1 class="h3 mb-3 fw-normal">Your Area is {{ registration.area }}</h1>
    <h1 class="h3 mb-3 fw-normal">Your State Name is {{ registration.state }}</h1>
    <h1 class="h3 mb-3 fw-normal">Your District Name is {{ registration.district }}</h1>
    <h1 class="h3 mb-3 fw-normal">Your Subdistrict Name is {{ registration.subdistrict }}</h1>
    <h1 class="h3 mb-3 fw-normal">Your Postoffice Name is {{ registration.postoffice }}</h1>
    <h1 class="h3 mb-3 fw-normal">Your Village/Area Name is {{ registration.village }}</h1>
    {% if registration.templename %}
    <h1 class="h3 mb-3 fw-normal">Your Templename Name is {{ registration.templename }}</h1>
    {% endif %}
    {% else %}
    <h1 class="h3 mb-3 fw-normal">You have been not approved yet for the Subscription we will send you an email when the admin will approve you</h1>
    {% endif %}
</div>


{% endblock content %}

registerform/templates/registerform/subdistrict_dropdown_list.html
<option value="">---------</option>
{% for subdistrict in subdistricts %}
<option value="{{ subdistrict }}">{{ forloop.counter }} {{ subdistrict }}</option>
{% endfor %}

registerform/templates/registerform/village_dropdown_list.html
<option value="">---------</option>
{% for village in villages %}
<option value="{{ village }}">{{ forloop.counter }} {{ village }}</option>
{% endfor %}