blogapp/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf import settings
import os

from personal.views import (
    home_screen_view,
    returnassetlink,
)

from account.views import(
    registration_view,
    logout_view,
    login_view,
    account_view,
    changepasswordview,
    sendotp,
    changepasswordform,
    resetpassword,
    resetpasswordview,
)

from registerform.views import(
    create_subscription,
    load_district,
    load_subdistrict,
    load_postoffice,
    see_subscription,
    load_village,
)

from post.views import(
    show_feed,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name='home'),
    path('post/', include('post.urls', 'post')),
    path('register/', registration_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('login/', login_view, name='login'),
    path('account/', account_view, name='account'),
    path('subscribe/', create_subscription, name='subscribe'),
    path('see_subscription/', see_subscription, name='see_subscription'),
    path('ajax/load-district', load_district, name='load-district'),
    path('ajax/load-subdistrict', load_subdistrict, name='load-subdistrict'),
    path('ajax/load-postoffice', load_postoffice, name='load-postoffice'),
    path('ajax/load-village', load_village, name='load-village'),
    path('feed/', show_feed, name='feed'),
    path('.well-known/assetlinks.json', returnassetlink),
    path('changepassword/', changepasswordview, name='changepassword'),
    path('sendotp/<phone>', sendotp, name='sendotp'),
    path('changepasswordform/<phone>/<otp>',
         changepasswordform, name='changepasswordform'),
    path('resetpassword/', resetpassword, name='resetpassword'),
    path('resetpasswordview/<phone>', resetpasswordview, name='resetpasswordview'),

    path('', include('pwa.urls')),
    url(r'session_security/', include('session_security.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from post.views import(
    create_post_view,
    edit_post_view,
    delPost,
    likePost,
    detail_post_view,
)

app_name = 'post'

urlpatterns = [
    path('create', create_post_view, name='create'),
    path('<pk>/edit', edit_post_view, name='edit'),
    path('<pk>/delete', delPost, name='delete'),
    path('like', likePost, name='likepost'),
    path('<pk>', detail_post_view, name='detail'),
]

post/models.py
from django.db import models
from account.models import Account

# Create your models here.
from django.conf import settings
from datetime import datetime


def upload_location(instance, filename):
    file_path = 'image/post/{author_id}/{title}-{datetiming}-{filename}'.format(
        author_id=str(instance.author.id), title=str(instance.title), filename=filename,
        datetiming=datetime.now().strftime("%d/%m/%Y %H:%M:%S")
    )
    return file_path


def upload_video_location(instance, filename):
    file_path = 'video/post/{author_id}/{title}-{datetiming}-{filename}'.format(
        author_id=str(instance.author.id), title=str(instance.title), filename=filename,
        datetiming=datetime.now().strftime("%d/%m/%Y %H:%M:%S")
    )
    return file_path


class Post(models.Model):
    title = models.CharField(max_length=50, null=False, blank=False)
    body = models.TextField(max_length=5000, null=True, blank=True)
    image = models.ImageField(upload_to=upload_location, null=True, blank=True)
    videofile = models.FileField(
        upload_to=upload_video_location, null=True, blank=True)
    date_published = models.DateTimeField(
        auto_now_add=True, verbose_name="date published")
    date_updated = models.DateTimeField(
        auto_now=True, verbose_name="date updateddate_updated")
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Like(models.Model):
    user = models.ManyToManyField(Account, related_name="likingUser")
    post = models.OneToOneField(Post, on_delete=models.CASCADE)

    @classmethod
    def like(cls, post, liking_user):
        obj, create = cls.objects.get_or_create(post=post)
        obj.user.add(liking_user)

    @classmethod
    def dislike(cls, post, disliking_user):
        obj, create = cls.objects.get_or_create(post=post)
        obj.user.remove(disliking_user)

    def getnooflikes(self):
        return self.user.count()

    def __str__(self):
        return str(self.post)

post/forms.py
from django import forms

from post.models import Post

class CreatePostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=['title','body','image','videofile']

class UpdatePostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=['title','body','image','videofile']

    def save(self,commit=True):
        post=self.instance
        post.title=self.cleaned_data['title']
        if self.cleaned_data['body']:
            post.body=self.cleaned_data['body']

        if self.cleaned_data['image']:
            post.image=self.cleaned_data['image']

        if self.cleaned_data['videofile']:
            post.videofile=self.cleaned_data['videofile']

        if commit:
            post.save()
        return post

post/views.py
from django.shortcuts import render, redirect, get_object_or_404
from registerform.models import RegistrationForm
from post.models import Post, Like
from operator import attrgetter
from post.forms import CreatePostForm, UpdatePostForm
from account.models import Account
from django.db.models import Q
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
import json
from django.http import HttpResponse

BLOG_POSTS_PER_PAGE = 10

# Create your views here.


def create_post_view(request):

    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('login')

    registration = RegistrationForm.objects.filter(user=request.user)
    if not registration:
        return redirect('subscribe')
    if not registration[0].is_approved:
        return redirect('see_subscription')
    if registration[0].membertype != 'Life Member':
        return redirect('feed')

    form = CreatePostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        author = Account.objects.filter(username=user.username).first()
        obj.author = author
        obj.save()
        return redirect('feed')

    context['form'] = form

    context['registration'] = registration[0]

    return render(request, 'post/create_post.html', context)


def edit_post_view(request, pk):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('login')

    registration = RegistrationForm.objects.filter(user=request.user)
    if not registration:
        return redirect('subscribe')
    if not registration[0].is_approved:
        return redirect('see_subscription')
    if registration[0].membertype != 'Life Member':
        return redirect('feed')

    post = get_object_or_404(Post, pk=pk)

    if request.POST:
        form = UpdatePostForm(request.POST or None,
                              request.FILES or None, instance=post)
        if form.is_valid():
            obj = form.save(commit=False)
            if request.POST.get('clear_image_image'):
                obj.image = None
            if request.POST.get('clear_image_videofile'):
                obj.videofile = None
            obj.save()
            context['success_message'] = "Updated"
            post = obj

    form = UpdatePostForm(
        initial={
            'title': post.title,
            'body': post.body or '',
            'image': post.image or None,
            'videofile': post.videofile or None,
        }
    )
    context['form'] = form
    context['registration'] = registration[0]
    return render(request, 'post/edit_post.html', context)


def get_post_queryset(request, query=None):
    queryset = []
    queries = query.split(" ")
    for q in queries:
        posts = Post.objects.filter(
            Q(title__icontains=q) |
            Q(body__icontains=q)
        ).distinct()

        for post in posts:
            is_liked = Like.objects.filter(post=post, user=request.user)
            likes = Like.objects.filter(post=post)
            if is_liked:
                post.is_liked = True
            if likes:
                post.nooflike = likes[0].getnooflikes()
            else:
                post.nooflike = 0
            queryset.append(post)

    return list(set(queryset))


def get_post_queryset_account(query=None, account=None):
    queryset = []
    queries = query.split(" ")
    for q in queries:
        posts = Post.objects.filter(author=account).filter(
            Q(title__icontains=q) |
            Q(body__icontains=q)
        ).distinct()

        for post in posts:
            queryset.append(post)

    return list(set(queryset))


def show_feed(request):
    if not request.user.is_authenticated:
        return redirect('login')
    registration = RegistrationForm.objects.filter(user=request.user)
    if not registration:
        return redirect('subscribe')
    if not registration[0].is_approved:
        return redirect('see_subscription')

    context = {}
    context['registration'] = registration[0]

    query = ''
    if request.GET:
        query = request.GET.get('q', '')
        context['query'] = str(query)

    posts = sorted(get_post_queryset(request, query),
                   key=attrgetter('date_updated'), reverse=True)

    page = request.GET.get('page', 1)
    posts_paginator = Paginator(posts, BLOG_POSTS_PER_PAGE)

    try:
        posts = posts_paginator.page(page)
    except PageNotAnInteger:
        posts = posts_paginator.page(BLOG_POSTS_PER_PAGE)
    except EmptyPage:
        posts = posts_paginator.page(posts_paginator.num_pages)

    context['posts'] = posts

    return render(request, 'post/feed.html', context)


def delPost(request, pk):
    if not request.user.is_authenticated:
        return redirect('login')
    registration = RegistrationForm.objects.filter(user=request.user)
    if not registration:
        return redirect('subscribe')
    if not registration[0].is_approved:
        return redirect('see_subscription')
    post_ = Post.objects.filter(pk=pk)
    post_.delete()
    return redirect('feed')


def likePost(request):
    resp = {}
    post_id = request.GET.get("likeId", "")
    post = Post.objects.get(pk=post_id)
    user = request.user
    like = Like.objects.filter(post=post, user=user)
    liked = False
    if like:
        Like.dislike(post, user)
        resp["nofolikes"] = Like.objects.filter(
            post=post).first().getnooflikes()
    else:
        liked = True
        Like.like(post, user)
        resp["nofolikes"] = Like.objects.filter(
            post=post).first().getnooflikes()

    resp["liked"] = liked
    response = json.dumps(resp)
    return HttpResponse(response, content_type="application/json")


def detail_post_view(request, pk):
    context = {}
    post = get_object_or_404(Post, pk=pk)
    is_liked = Like.objects.filter(post=post, user=request.user)
    likes = Like.objects.filter(post=post)
    if is_liked:
        post.is_liked = True
    if likes:
        post.nooflike = likes[0].getnooflikes()
    else:
        post.nooflike = 0
    context['post'] = post
    return render(request, 'post/detail_post.html', context)

post/templates/post/snippets/post_pagination.html
<div class="d-flex flex-column m-auto pagination mt-5">
    <nav aria-label="Page navigation">
    <ul class="pagination pg-grey justify-content-center">
        {% if posts.has_next %}
            <li class="page-item">
              <a class="infinite-more-link page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ posts.next_page_number }}">Next</a>
            </li>
        {% endif %}
    </ul>
    </nav>
    </div>

post/templates/post/snippets/post_snippet.html
<style type="text/css">
	.card{
		max-width: 700px;
	}
	.card-body{
		padding: 20px;
		width: 100%;
	}
</style>
{% if post %}
<div class="infinite-item mt-4" id="{{post.pk}}">
<div class="container">
	<div class="row">
		<!-- Blog Post -->
		<div class="card">
            {% if post.image %}
				<img class="card-img-top" src="{{post.image.url}}">
            {% endif %}

            {% if post.videofile %}
            <video controls>
                <source src="{{post.videofile.url}}" type="video/mp4">
              Your browser does not support the video tag.
              </video>
            {% endif %}
			
			<div class="card-body mt-2 mb-2">

					<a style="text-decoration: none;" href="{% url 'post:detail' post.pk %}"><h2 class="card-title">{{post.title}}</h2></a>

                {% if post.body %}
				<p class="card-text">{{post.body}}</p>
                {% endif %}
				<p class="card-text" id="nofolikes{{post.pk}}">Likes - {{post.nooflike}}</p>
				{% if post.author == request.user %}
					<a href="{% url 'post:edit' post.pk %}" class="btn btn-warning" style="color: white;">Update</a>
					<button class="btn btn-light like" style="border-color: red;" id="{{post.pk}}">
						{% if post.is_liked %}
					  <a href="{% url 'post:likepost' %}" style="color: red;text-decoration: none;" id="like_text{{post.pk}}">Liked</a>
					  {% else %}
					  <a href="{% url 'post:likepost' %}" style="color: red;text-decoration: none;" id="like_text{{post.pk}}">Like</a>
					  {% endif %}
					  </button>
					<form style="display: inline;" method="POST" action="{% url 'post:delete' post.pk %}" id="{{post.pk}}" class="delete">
						{% csrf_token %}
						<input type='submit' value="Delete" class="btn btn-danger">
					</form>
					{% else %}
					<button class="btn btn-light like" style="border-color: red;" id="{{post.pk}}">
						{% if post.is_liked %}
					  <a href="{% url 'post:likepost' %}" style="color: red;text-decoration: none;" id="like_text{{post.pk}}">Liked</a>
					  {% else %}
					  <a href="{% url 'post:likepost' %}" style="color: red;text-decoration: none;" id="like_text{{post.pk}}">Like</a>
					  {% endif %}
					  </button>
				{% endif %}
			</div>
			<div class="card-footer text-muted">
			  Updated on {{post.date_updated}} by {{post.author}}
			</div>
		</div>
	</div>
</div>
</div>
{% else %}
<div class="container">
<div class="row">
<div class="card m-auto">
<div class="card-body mt-2 mb-2">
<h2 class="card-title">
	No results
</h2>
<p class="card-text">There were no results matching your search: "{{query}}"</p>
</div>
</div>
</div>
</div>
{% endif %}